"""internacao modelos e rotas

Revision ID: 153137b85b72
Revises: 5ea6314d6c33
Create Date: 2025-08-16 18:26:58.205234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153137b85b72'
down_revision = '5ea6314d6c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('leito', sa.String(length=50), nullable=True),
    sa.Column('diagnostico', sa.String(length=255), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('data_alta', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('fk_internacao_paciente_id_paciente')),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissional.id'], name=op.f('fk_internacao_profissional_id_profissional')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internacao'))
    )
    with op.batch_alter_table('internacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internacao_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internacao_profissional_id'), ['profissional_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internacao_profissional_id'))
        batch_op.drop_index(batch_op.f('ix_internacao_paciente_id'))

    op.drop_table('internacao')
    # ### end Alembic commands ###
