"""prontuario e prescricao

Revision ID: 1782ca2b35c7
Revises: 67d83b64a5a1
Create Date: 2025-08-16 18:09:23.821391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1782ca2b35c7'
down_revision = '67d83b64a5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescricao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('fk_prescricao_paciente_id_paciente')),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissional.id'], name=op.f('fk_prescricao_profissional_id_profissional')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescricao'))
    )
    with op.batch_alter_table('prescricao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescricao_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricao_profissional_id'), ['profissional_id'], unique=False)

    op.create_table('prontuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('resumo', sa.String(length=255), nullable=False),
    sa.Column('anotacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('fk_prontuario_paciente_id_paciente')),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissional.id'], name=op.f('fk_prontuario_profissional_id_profissional')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prontuario'))
    )
    with op.batch_alter_table('prontuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prontuario_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prontuario_profissional_id'), ['profissional_id'], unique=False)

    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('lido', sa.Boolean(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consulta.id'], name=op.f('fk_notificacao_consulta_id_consulta')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_notificacao_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notificacao'))
    )
    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacao_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_usuario_profissional_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_profissional_id'), ['profissional_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuario_paciente_id'), ['paciente_id'], unique=False)

    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacao_usuario_id'))

    op.drop_table('notificacao')
    with op.batch_alter_table('prontuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prontuario_profissional_id'))
        batch_op.drop_index(batch_op.f('ix_prontuario_paciente_id'))

    op.drop_table('prontuario')
    with op.batch_alter_table('prescricao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescricao_profissional_id'))
        batch_op.drop_index(batch_op.f('ix_prescricao_paciente_id'))

    op.drop_table('prescricao')
    # ### end Alembic commands ###
