"""teleconsulta e anexos + publico/me/relatorios

Revision ID: 5ea6314d6c33
Revises: 1782ca2b35c7
Create Date: 2025-08-16 18:19:27.044021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea6314d6c33'
down_revision = '1782ca2b35c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teleconsulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('fk_teleconsulta_paciente_id_paciente')),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissional.id'], name=op.f('fk_teleconsulta_profissional_id_profissional')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teleconsulta'))
    )
    with op.batch_alter_table('teleconsulta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teleconsulta_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teleconsulta_profissional_id'), ['profissional_id'], unique=False)

    op.create_table('tele_anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teleconsulta_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=512), nullable=False),
    sa.Column('mimetype', sa.String(length=100), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teleconsulta_id'], ['teleconsulta.id'], name=op.f('fk_tele_anexo_teleconsulta_id_teleconsulta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tele_anexo'))
    )
    with op.batch_alter_table('tele_anexo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tele_anexo_teleconsulta_id'), ['teleconsulta_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tele_anexo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tele_anexo_teleconsulta_id'))

    op.drop_table('tele_anexo')
    with op.batch_alter_table('teleconsulta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teleconsulta_profissional_id'))
        batch_op.drop_index(batch_op.f('ix_teleconsulta_paciente_id'))

    op.drop_table('teleconsulta')
    # ### end Alembic commands ###
